### ISSUE TITLE
sandboxes-gpte.ocp4-sustainable.event-1 missing libs

### ISSUE THREAD

**Issue by piparul** [piparul/kepler-labdemo-bookbag#1]
Hi @newgoliath 

I tested the `sandboxes-gpte.ocp4-sustainable.event-1` following the steps mentioned here
https://github.com/piparul/kepler-labdemo-bookbag/blob/main/workshop/content/exercise1.adoc

- The step `make deploy IMG=quay.io/sustainable_computing_io/kepler-operator:latest` needs the bastion host to be installed with `make`. Do we expect the students to install `make` or can we have the bastion host pre-installed with `make`?

- we also need `go 1.18`. I did a manual `sudo dnf install -y go` and that installed `go version go1.17.12 linux/amd64`

**Comment by newgoliath** [comment]
No make!  wow!  We can add all these things.

Which RHEL has go 1.18?

Would you be interested in having ALL this automated - including the lab instructions - so you can focus on more Kepler use cases?

**Comment by piparul** [comment]
That would be very helpful. I am not sure about which Rhel has go 1.18. But this web page has the following information
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/8.7_release_notes/index

```
The following performance monitoring tools have been updated in RHEL 8.7:

PCP 5.3.7
Grafana 7.5.13
Updated compiler toolsets
The following compiler toolsets have been updated in RHEL 8.7:

GCC Toolset 12
LLVM Toolset 14.0.6
Rust Toolset 1.62
Go Toolset 1.18
```

Is it possible to test with 8.7 release and see if it works?

**Comment by piparul** [comment]
For now I am going to install Go binary archive from their official page https://go.dev/dl/ to continue with the end to end lab testing and update this issue with anything that is missing.

**Comment by piparul** [comment]
FYI I ran the following to set up the env.

```
sudo dnf install -y make
wget https://go.dev/dl/go1.18.10.linux-amd64.tar.gz
tar -xzf  go1.18.10.linux-amd64.tar.gz
cp -R go /usr/local/
```

Added following in `~/.bashrc`

``` 
PATH=$PATH:/usr/local/go/bin
export PATH
```
Check the go version
```
go version
go version go1.18.10 linux/amd64
```

cc @newgoliath @rhjcd

**Comment by newgoliath** [comment]
This should be fixed.
