### ISSUE TITLE
[BLOCKING] Unable to fetch the Bearer token

### ISSUE THREAD

**Issue by piparul** [piparul/kepler-labdemo-bookbag#2]
Running the following while connected to the bastion host shows `error: no token is currently in use for this session`

### Steps to reproduce

```
ssh lab-user@bastion.xxxx.xxxx.xxx.com
oc whoami --show-token
error: no token is currently in use for this session
```
We are blocked with further testing of the lab until this issue is resolved.
cc: @newgoliath @rhjcd

**Comment by newgoliath** [comment]
sudo -i; su ec2-user
